### ISSUE TITLE
network issue/delay causes electron-notarize to fail even though notarization succeeded.

### ISSUE THREAD

**Issue by Kilian** [electron-userland/electron-notarize#2] opened 2019-05-21 13:05 UTC
Not sure how actionable this is but I just notarized an app and the CLI failed with the following message:
```
[...]
  electron-notarize zip succeeded, attempting to upload to apple +9s
  electron-notarize upload success +2m
  electron-notarize found UUID: <snip> +0ms
  electron-notarize checking notarization status:<snip> +4ms
Error: Failed to check status of notarization request: <snip>

2019-05-21 14:51:26.892 altool[2752:56346] *** Error: Apple Services operation failed. Could not find the RequestUUID.

    at /Users/kilian/workspace/personal/myapp/node_modules/electron-notarize/src/index.ts:98:11
[...]
```
(uuid removed, don't know if that's sensitive)

...and then moments later I received an email from Apple about how everything went fine and I should go and distribute my app.

A second attempt did work without any issues so it's likely some network + timing issue, but I thought I'd mention it anyway.

**Comment by lane-c-wagner** [comment] 2019-05-26 15:32
I'm seeing this as well. Not sure the cause, but getting an email from apple saying it was successful but  CLI states it couldn't find request UUID.

**Comment by lane-c-wagner** [comment] 2019-05-29 14:15
Are there any maintainers that can look at this PR? Its actually unusable for some users (including myself) right now.

**Comment by Kilian** [comment] 2019-05-29 14:31
To be fair I think this is mostly a timing issue on Apple’s servers side. The 30s timeout already feels long but maybe a configurable timeout could help you?

**Comment by lane-c-wagner** [comment] 2019-05-29 14:40
I don't think there is a 30 second waiting time before the first status request is sent.. but I could be wrong. It looked to me like it polls immediately after creating the notarization job, not giving the apple servers time to create the UUID. A configurable time would work, we just need to make sure whatever solution we find gets built into electron-builder as well if it is going to use electron-notarize as a dependency.

**Comment by raymondjacobson** [comment] 2019-05-30 23:02
I am also running into this on CI (circle) reproducibly and haven't gotten it to work once :/

**Comment by MarshallOfSound** [comment] 2019-05-31 00:32
Fixed in #4

**Closed by MarshallOfSound** 2019-05-31 00:32 UTC

**Comment by chris-araman** [comment] 2019-10-18 16:14
We started hitting this error again over the past few days. It seems the lag in the Apple API has increased. We've temporarily increased the initial timeout from 10s to 30s in our fork. Would the authors be interested in a pull request for such a trivial change?
https://github.com/fuze/electron-notarize/commit/3c29467960ef9d5355e3788d97203b266d5bfc6c

**Comment by chris-araman** [comment] 2019-10-18 16:19
Nevermind. Looks like https://github.com/electron/electron-notarize/pull/14 is on the right track.

**Comment by brunolemos** [comment] 2019-11-01 23:50
Getting this today for the first time.
